version: "3"
services:
  swagger-server:
    image: stoplight/prism:3
    container_name: "swagger-server"
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /openapi.yml
    volumes:
      - ./openapi.yml:/openapi.yml
